config/routes.rb
Scrap::Application.routes.draw do
  resources :scrappings do
     put :fly, on: :member
 end
  
  

end

app/models/scrapping.rb
class Scrapping < ActiveRecord::Base
  attr_accessible :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scrappings_controller.rb
class ScrappingsController < ApplicationController
  # GET /scrappings
  # GET /scrappings.json
  def index
    @scrappings = Scrapping.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scrappings }
    end
  end

  # GET /scrappings/1
  # GET /scrappings/1.json

  
  def show
    @scrapping = Scrapping.find(params[:id])
    url = "http://embed.ly/docs/explore/oembed?url=#{@scrapping.url}"
     require 'net/http'
     require 'rubygems'
     require 'nokogiri'
     require 'open-uri'

    doc = Nokogiri::HTML(open(url))
    logger.debug "#{doc}\n\n\n\n\n\n"
    @provider_url = ""
    @provider_url <<  doc.css('#provider_url').text
    @e_provider_url = ""
    @e_provider_url <<  doc.css('.e_provider_url').text
    @provider_name = ""
    @provider_name <<  doc.css('#provider_name').text
    @e_provider_name = ""
    @e_provider_name << doc.css('.e_provider_name').text
    @type = ""
    @type << doc.css('#type').text
    @e_type = ""
    @e_type << doc.css('.e_type').text
    @title = ""
    @title << doc.css('#title').text
    @e_title = ""
    @e_title << doc.css('.e_title').text
    @description = ""
    @description << doc.css('#description').text
    @e_description = ""
    @e_description = doc.css('.e_description').text
    @url = ""
    @url = doc.css('#url').text
    @e_url = ""
    @e_url = doc.css('.e_url').text
    @width = ""
    @width = doc.css('#width').text
    @e_width = ""
    @e_width = doc.css('.e_width').text
    @height = ""
    @height = doc.css('#height').text
    @e_height = ""
    @e_height = doc.css('.e_height').text
    @html = ""
    @html = doc.css('#html').text
    @e_html = ""
    @e_html = doc.css('.e_html').text
    @thumbnail = ""
    @thumbnail = doc.css('#thumbnail').text
    @e_thumbnail = ""
    @e_thumbnail = doc.css('#embedcontent img').text
    @thumbnail_url = ""
    @thumbnail_url = doc.css('#thumbnail_url').text
    @e_thumbnail_url = ""
    @e_thumbnail_url = doc.css('.e_thumbnail_url').text
    @thumbnail_width = ""
    @thumbnail_width = doc.css('#thumbnail_width').text
    @e_thumbnail_width = ""
    @e_thumbnail_width = doc.css('.e_thumbnail_width').text
    @thumbnail_height = ""
    @thumbnail_height = doc.css('#thumbnail_height').text
    @e_thumbnail_height = ""
    @e_thumbnail_height = doc.css('.e_thumbnail_height').text
    @author = ""
    @author = doc.css('#author').text
    @e_author = ""
    @e_author = doc.css('.e_author').text
    @author_url = ""
    @author_url = doc.css('#author_url').text
    @e_author_url = ""
    @e_author_url = doc.css('.e_author_url').text
    @display = ""
    @display = doc.css('#display').text
    @e_display = ""
    @e_display = doc.css('.e_display').text

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scrapping }
    end
  end

  # GET /scrappings/new
  # GET /scrappings/new.json
  def new
    @scrapping = Scrapping.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scrapping }
    end
  end

  # GET /scrappings/1/edit
  def edit
    @scrapping = Scrapping.find(params[:id])
  end

  # POST /scrappings
  # POST /scrappings.json
  def create
    @scrapping = Scrapping.new(params[:scrapping])
    

    respond_to do |format|
      if @scrapping.save
        format.html { redirect_to @scrapping, notice: 'Scrapping was successfully created.' }
        format.json { render json: @scrapping, status: :created, location: @scrapping }
      else
        format.html { render action: "new" }
        format.json { render json: @scrapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scrappings/1
  # PUT /scrappings/1.json
  def update
    @scrapping = Scrapping.find(params[:id])

    respond_to do |format|
      if @scrapping.update_attributes(params[:scrapping])
        format.html { redirect_to @scrapping, notice: 'Scrapping was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scrapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrappings/1
  # DELETE /scrappings/1.json
  def destroy
    @scrapping = Scrapping.find(params[:id])
    @scrapping.destroy

    respond_to do |format|
      format.html { redirect_to scrappings_url }
      format.json { head :no_content }
    end
  end
  
  def fly
      @scrapping = Scrapping.find(params[:id])
      @scrapping.url = params[:scrapping][:url]
      @scrapping.save
      logger.debug "url es:  #{params[:scrapping][:url]}"
      url = "http://embed.ly/docs/explore/oembed?url=#{@scrapping.url}"
       require 'net/http'
       require 'rubygems'
       require 'nokogiri'
       require 'open-uri'
      logger.debug "url es:  #{url}"
      doc = Nokogiri::HTML(open(url))
      logger.debug "#{doc}\n\n\n\n\n\n"
      @provider_url = ""
      @provider_url <<  doc.css('#provider_url').text
      @e_provider_url = ""
      @e_provider_url <<  doc.css('.e_provider_url').text
      @provider_name = ""
      @provider_name <<  doc.css('#provider_name').text
      @e_provider_name = ""
      @e_provider_name << doc.css('.e_provider_name').text
      @type = ""
      @type << doc.css('#type').text
      @e_type = ""
      @e_type << doc.css('.e_type').text
      @title = ""
      @title << doc.css('#title').text
      @e_title = ""
      @e_title << doc.css('.e_title').text
      @description = ""
      @description << doc.css('#description').text
      @e_description = ""
      @e_description = doc.css('.e_description').text
      @url = ""
      @url = doc.css('#url').text
      @e_url = ""
      @e_url = doc.css('.e_url').text
      @width = ""
      @width = doc.css('#width').text
      @e_width = ""
      @e_width = doc.css('.e_width').text
      @height = ""
      @height = doc.css('#height').text
      @e_height = ""
      @e_height = doc.css('.e_height').text
      @html = ""
      @html = doc.css('#html').text
      @e_html = ""
      @e_html = doc.css('.e_html').text
      @thumbnail = ""
      @thumbnail = doc.css('#thumbnail').text
      @e_thumbnail = ""
      @e_thumbnail = doc.css('#embedcontent img').text
      @thumbnail_url = ""
      @thumbnail_url = doc.css('#thumbnail_url').text
      @e_thumbnail_url = ""
      @e_thumbnail_url = doc.css('.e_thumbnail_url').text
      @thumbnail_width = ""
      @thumbnail_width = doc.css('#thumbnail_width').text
      @e_thumbnail_width = ""
      @e_thumbnail_width = doc.css('.e_thumbnail_width').text
      @thumbnail_height = ""
      @thumbnail_height = doc.css('#thumbnail_height').text
      @e_thumbnail_height = ""
      @e_thumbnail_height = doc.css('.e_thumbnail_height').text
      @author = ""
      @author = doc.css('#author').text
      @e_author = ""
      @e_author = doc.css('.e_author').text
      @author_url = ""
      @author_url = doc.css('#author_url').text
      @e_author_url = ""
      @e_author_url = doc.css('.e_author_url').text
      @display = ""
      @display = doc.css('#display').text
      @e_display = ""
      @e_display = doc.css('.e_display').text
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrappings_helper.rb
module ScrappingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scrappings/_fly.html.erb
<div>
	<span><%= "#{@title} #{@e_title}" %></span>
</div>
<div>
	<span><%= "#{@thumbnail} #{@e_thumbnail}" %></span>
	<span><%= image_tag("#{@e_thumbnail_url}")%></span>
</div>

app/views/scrappings/_form.html.erb
<% form_for @scrapping do |f| %>
  <% if @scrapping.errors.any? %>
    <div id="error_explanation">	
      <h2><%= pluralize(@scrapping.errors.count, "error") %> prohibited this scrapping from being saved:</h2>

      <ul>
      <% @scrapping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scrappings/edit.html.erb
<h1>Editing scrapping</h1>

<%= render 'form' %>

<%= link_to 'Show', @scrapping %> |
<%= link_to 'Back', scrappings_path %>

app/views/scrappings/fly.js.erb
$('#preview').html("<%= escape_javascript( render :partial => 'fly') %>");

app/views/scrappings/index.html.erb
<h1>Listing scrappings</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scrappings.each do |scrapping| %>
  <tr>
    <td><%= scrapping.url %></td>
    <td><%= link_to 'Show', scrapping %></td>
    <td><%= link_to 'Edit', edit_scrapping_path(scrapping) %></td>
    <td><%= link_to 'Destroy', scrapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scrapping', new_scrapping_path %>

app/views/scrappings/new.html.erb
<h1>New scrapping</h1>

<%= render 'form' %>

<%= link_to 'Back', scrappings_path %>

app/views/scrappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<!--
  <b>Url:</b>
  <%= @scrapping.url %>
</p>

<div>
	<span><%= "#{@provider_url} #{@e_provider_url}" %></span>
</div>

<div>
	<span><%= "#{@provider_name} #{@e_provider_name}" %></span>
</div>
<div>
	<span><%= "#{@type} #{@e_type}" %></span>
</div>
<div>
	<span><%= "#{@title} #{@e_title}" %></span>
</div>
<div>
	<span><%= "#{@description} #{@e_description}" %></span>
</div>
<div>
	<span><%= "#{@url} #{@e_url}" %></span>
</div>
<div>
	<span><%= "#{@widht} #{@e_widht}" %></span>
</div>
<div>
	<span><%= "#{@height} #{@e_height}" %></span>
</div>
<div>
	<span><%= "#{@html} #{@e_html}" %></span>
</div>

<div>
	<span><%= "#{@thumbnail} #{@e_thumbnail}" %></span>
	<span><%= image_tag("#{@e_thumbnail_url}")%></span>
</div>
<div>
	<span><%= "#{@thumbnail_url} #{@e_thumbnail_url}" %></span>
</div>
<div>
	<span><%= "#{@thumbnail_width} #{@e_thumbnail_width}" %></span>
</div>
<div>
	<span><%= "#{@thumbnail_height} #{@e_thumbnail_height}" %></span>
</div>
<div>
	<span><%= "#{@author} #{@e_author}" %></span>
</div>
<div>
	<span><%= "#{@author_url} #{@e_author_url}" %></span>
</div>
 -->

<%= form_for @scrapping, url: fly_scrapping_path(@scrapping), remote: true do |f| %>
	<%= f.text_field :url %>
	<%= f.submit "scrap" %>
<% end %>

<div id="preview"></div>

<%= link_to 'Edit', edit_scrapping_path(@scrapping) %> |
<%= link_to 'Back', scrappings_path %>